// <auto-generated />
using System;
using BibliotecaBlazor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BibliotecaBlazor.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20251121031348_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BibliotecaBlazor.Models.Devolucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaDevolucion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechadevolucion");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("integer")
                        .HasColumnName("prestamoid");

                    b.HasKey("Id")
                        .HasName("pk_devoluciones");

                    b.HasIndex("PrestamoId")
                        .HasDatabaseName("ix_devoluciones_prestamoid");

                    b.ToTable("devoluciones");
                });

            modelBuilder.Entity("BibliotecaBlazor.Models.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("carrera");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cedula");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Seccion")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("seccion");

                    b.Property<int>("Semestre")
                        .HasColumnType("integer")
                        .HasColumnName("semestre");

                    b.HasKey("Id")
                        .HasName("pk_estudiantes");

                    b.ToTable("estudiantes");
                });

            modelBuilder.Entity("BibliotecaBlazor.Models.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("autor");

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("integer")
                        .HasColumnName("cantidaddisponible");

                    b.Property<string>("CaratulaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("caratulaurl");

                    b.Property<string>("TituloLibro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulolibro");

                    b.HasKey("Id")
                        .HasName("pk_libros");

                    b.ToTable("libros");
                });

            modelBuilder.Entity("BibliotecaBlazor.Models.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Devuelto")
                        .HasColumnType("boolean")
                        .HasColumnName("devuelto");

                    b.Property<bool>("EsInterno")
                        .HasColumnType("boolean")
                        .HasColumnName("esinterno");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer")
                        .HasColumnName("estudianteid");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechadevolucion");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechasalida");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.HasKey("Id")
                        .HasName("pk_prestamos");

                    b.HasIndex("EstudianteId")
                        .HasDatabaseName("ix_prestamos_estudianteid");

                    b.ToTable("prestamos");
                });

            modelBuilder.Entity("BibliotecaBlazor.Models.PrestamoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("LibroId")
                        .HasColumnType("integer")
                        .HasColumnName("libroid");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("integer")
                        .HasColumnName("prestamoid");

                    b.HasKey("Id")
                        .HasName("pk_prestamosdetalles");

                    b.HasIndex("LibroId")
                        .HasDatabaseName("ix_prestamosdetalles_libroid");

                    b.HasIndex("PrestamoId")
                        .HasDatabaseName("ix_prestamosdetalles_prestamoid");

                    b.ToTable("prestamosdetalles");
                });

            modelBuilder.Entity("BibliotecaBlazor.Models.Devolucion", b =>
                {
                    b.HasOne("BibliotecaBlazor.Models.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("BibliotecaBlazor.Models.Prestamo", b =>
                {
                    b.HasOne("BibliotecaBlazor.Models.Estudiante", "Estudiante")
                        .WithMany("Prestamos")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("BibliotecaBlazor.Models.PrestamoDetalle", b =>
                {
                    b.HasOne("BibliotecaBlazor.Models.Libro", "Libro")
                        .WithMany("PrestamoDetalles")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliotecaBlazor.Models.Prestamo", "Prestamo")
                        .WithMany("Detalles")
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Libro");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("BibliotecaBlazor.Models.Estudiante", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("BibliotecaBlazor.Models.Libro", b =>
                {
                    b.Navigation("PrestamoDetalles");
                });

            modelBuilder.Entity("BibliotecaBlazor.Models.Prestamo", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
